#+TITLE: Tarea 1

- Mezcla los comandos =httppie=, =jq= y =csvkit= para descargar las películas de *Star Wars* y guardar los campos de   
  =title,episode_id,director,producer,release_date,opening_crawl= en una base de
  datos =sqlite= llamada =star_wars.db=.

- Usando =bash= crea un programa que descargue todas los /resources/ de *SWAPI*

  #+BEGIN_EXAMPLE shell 
  http GET http://swapi.co/api/
  #+END_EXAMPLE

  y guárdalos en =jsons= separados usando como nombres de archivo la llave del
  =json=.

  Toma en cuenta la paginación. Al final deberás de tener sólo 7 archivos.

  Procesa estos archivos con las herramientas del primer inciso de la tarea. Al
  final deberías de tener 7 tablas en =star_wars.db=

- Repite el inciso anterior, pero ahora usando =aws= y =parallel=. Crea 7 instancias de =Amazon EC2=,
  y en cada una procesa como antes. Distribuye los archivos de ejecución y luego tráelos a tu máquina local para 
  guardarlos en una base de datos =sqlite=.

  *NOTA* ¡No olvides apagar las máquinas!
